version: "3.1"
services:

  sharing:
    build: .

  sharingDB:
    image: postgres
    environment:
      - POSTGRES_DB=propra
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data:/var/lib/postgres/data

