version: "3.1"
services:

  sharing:
    build: .
    ports:
      - "8080:8080"

  sharingDB:
    image: postgres
    environment:
      - POSTGRES_DB=propra
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./data:/var/lib/postgres/data

  propay:
    image: propra/propay
    volumes:
      - ./data:/code/data

